PREFIX movieontology: <http://www.movieontology.org/2009/10/01/movieontology.owl#>
SELECT ?title ?actor
WHERE {
  ?movie a movieontology:Movie.
  ?movie movieontology:title ?title.
  ?movie movieontology:hasActor ?actor.
}